### ISSUE TITLE
Format of Nodes

### ISSUE THREAD

**Issue by bhupiiidx** [davidmnoll/chkflow#1]
Can You please write more on readme file and format of nodes

**Comment by davidmnoll** [comment]
@bhupiiidx  --- sure just saw this, will do

**Comment by davidmnoll** [comment]
![image](https://user-images.githubusercontent.com/12936973/156870737-3e609cd0-a0c4-4843-a0ea-83523f1315b1.png)

@bhupiiidx

**Comment by davidmnoll** [comment]
I added that quick tidbit at the bottom of the readme.  I will try to add more, but in the meantime, lmk if you have any questions, I can re-open this
